ToDoList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.home_view, name='home'),
    path('employee/<int:id>', views.detail_view, name='detail'),
    path('employee/<int:id>/export', views.export_csv, name='export'),
    path('api/task/<int:id>', views.task, name='task'),
    path('api/tasks', views.tasks_list, name='tasks')
    
    
    
]

core/models.py
from django.db import models


class Employee(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500, blank=True)
    

class Task(models.Model):
    
    class Status(models.IntegerChoices):
        NEW = 1, 'Nowe'
        COMPLETED = 2, 'Zrealizowane'
        
    class Category(models.IntegerChoices):
        FRONT = 1, 'FrontEnd'
        BACK = 2, 'BackEnd'
    
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)
    prediction = models.DateField()
    status = models.IntegerField(
        choices=Status.choices,
        default=1
    )
    # TODO: Category as manytomany
    category = models.IntegerField(choices=Category.choices, null=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    
    


    

core/forms.py
from django.forms import ModelForm
from django import forms
from . import models


class AddEmployee(ModelForm):
    class Meta:
        model = models.Employee
        fields = [
            'name',
            'description',
        ]
        labels = {
            'name': "Imię i nazwisko",
            'description': "Opis"
        }
        widgets = {
    
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'description': forms.Textarea(attrs={'class':'form-control'})
        }

core/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .serializers import TaskSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
import csv

from .models import Task, Employee
from .forms import AddEmployee


def home_view(request):
    if request.method == "POST":
        form = AddEmployee(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return redirect('core:detail', instance.pk)
    else:
        form = AddEmployee()

    employees = Employee.objects.all().order_by('-name')
    context = {
        'form': form,
        'employees': employees
    }
    return render(request, 'core/home.html',  context)

def detail_view(request, id):
    employee = get_object_or_404(Employee, id=id)
    tasks = Task.objects.filter(employee=employee)
    context = {
        'employee': employee,
        'tasks': tasks
    }
    return render(request, 'core/detail.html', context)


def export_csv(request, id):
    # TODO: Export friendly names for status and category
    employee = get_object_or_404(Employee, id=id)
    tasks = Task.objects.filter(employee=employee)
    response = HttpResponse('text/csv')
    response['Content-Disposition'] = 'attachment; filename=' + employee.name + '.csv'
    writer = csv.writer(response)
    writer.writerow([
        'ID', 
        'Name', 
        'Description', 
        'Created', 
        'Prediction',
        'Status',
        'Category'
    ])
    tsks = tasks.values_list(
        'id',
        'name',
        'description',
        'created',
        'prediction',
        'status',
        'category'
    )
    for t in tsks:
        writer.writerow(t)
    return response


# Api
@api_view(['GET', 'POST'])
def tasks_list(request):
    if request.method == 'GET':
        if 'employee' in request.query_params:
            tasks = Task.objects.filter(employee_id = request.query_params['employee'])
        else:
            tasks = Task.objects.all()
            
        if 'sort' in request.query_params:
            if request.query_params['sort'] == 'category':
                tasks = tasks.order_by('category')
                
            if request.query_params['sort'] =='-category':
                tasks = tasks.order_by('-category')
                
            if request.query_params['sort'] =='date':
                tasks = tasks.order_by('prediction')
                
            if request.query_params['sort'] == '-date':
                tasks = tasks.order_by('-prediction')

        tasks_serializer = TaskSerializer(tasks, many=True)
        return Response(tasks_serializer.data) 
    
    if request.method == 'POST':
        serializer = TaskSerializer(data=request.data)
        employee_id = request.data.get('employee') 
        employee = Employee.objects.get(id=employee_id)
        if serializer.is_valid():
            serializer.save(employee=employee)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        print(request.data)
        return Response(status=status.HTTP_400_BAD_REQUEST)    
    
    
@api_view(['PATCH', 'DELETE'])
def task(request, id):
    task = Task.objects.get(id=id)
    if not task:
        return Response(status.HTTP_204_NO_CONTENT)
    
    if request.method == 'PATCH':
        task.status = request.data.get('status')
        task.save()
        return Response(status=status.HTTP_200_OK)
        
    if request.method == 'DELETE':
        task.delete()
        return Response(status=status.HTTP_200_OK)
        
    return Response()

        

core/templates/base.html
{% load static %}
<!DOCTYPE ht ml>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.bundle.js' %}"></script>
    <script src="https://kit.fontawesome.com/bee8d9d382.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="{% static 'js/base.js' %}"></script>
    <title>ToDoList</title>
</head>

<body>
    <div class="container-xl border">
        <nav class="navbar navbar-expand-lg sticky-top navbar-light">
            <a class="col-8 navbar-brand fs-2 m-color" href="{% url 'core:home' %}">ToDoList</a>
        </nav>
        {% block 'content' %}


        {% endblock 'content' %}
    </div>
</body>

</html>

core/templates/core/detail.html
{% extends 'base.html' %}
{% block 'content' %}
<main id="e-list">

    <header class="row border-bottom header ptb">
        <div class="col-sm-6">
            <span class="fs-2"><i class="fa-solid fa-people-roof" id="employee" data-id="{{ employee.id }}"></i> {{ employee.name }}</span>
            <p>{{ employee.description }}</p>
        </div>
        <div class="col-sm-6 action align-items-center" id="action">
            <span class="fs-2" data-bs-toggle="modal" data-bs-target="#t-add">
                <i class="fa-solid fa-plus" style="margin-right: 10px;"> </i> Dodaj zadanie
            </span>
        </div>
        <div class="col-sm-3" id="filcon">
            Filtrowanie 
            <select name="filter" id="filter" class="form-control"> 
                <option value="-category">Kategoria (rosnąco)</option>
                <option value="category">Kategoria (malejąco)</option>
                <option value="date">Data (rosnąco)</option>
                <option value="-date">Data (malejąco)</option>
            </select>
        </div>
        <div class="col-sm-9 action align-items-center e-actions fs-1">
            <i class="fa-solid fa-file-export" id="file-export" title="Eksport do pliku csv"></i>
        </div>
    </header>

    <section class="tasks">
        <h1>Nowe</h1>
        <div id="t-new">
           
        </div>
    </section>
    <section class="tasks">
        <h1>Wykonane</h1>
        <div id="t-done">

        </div>
    </section>
    
</main>
<div class="modal" tabindex="-1" id="t-add">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Dodaj zadanie</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            {% csrf_token %}
            <form class="form-group" id="t-form">
                <div class="modal-body">
                    <input class="form-control" type="text" name="name" placeholder="Tytuł" required>
                    <textarea class="form-control" name="desciprtion" placeholder="Opis" required> </textarea>
                    <input class="form-control" type="date" name="prediction" placeholder="Przewidywana data wykonania" required>
                    <input type="hidden" name="status" value="1" required>
                    <select class="form-control" name="category" required>
                        <option value="1">FrontEnd</option>
                        <option value="2">BackEnd</option>
                    </select>
                    <input type="hidden" name="employee" value="{{ employee.id }}" required>
                    <div class="invalid-feedback">
                        Niepoprawne dane (Wszystkie pola są obowiązkowe)
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Zamknij</button>
                    <button type="button" class="btn btn-primary" id="t-save">Dodaj</button>
                </div>
            </form>    
        </div>
    </div>
</div>
{% endblock 'content' %}

core/templates/core/home.html
{% extends 'base.html' %}
{% block 'content' %}
<main id="e-list">
    <header class="row fs-2 border-bottom header ptb"> 
        <div class="col-sm-6">
            <i class="fa-solid fa-people-roof"></i> Lista pracowników
        </div>
        <div class="col-sm-6 action">
            <span data-bs-toggle="modal" data-bs-target="#e-add">
                <i class="fa-solid fa-plus" style="margin-right: 10px;"> </i> Dodaj pracownika
            </span>
        </div>

    </header>
    {% for employee in employees %}
    <div class="employee row fs-3">
        <span class="e-name col-10 task" data-bs-toggle="collapse" data-bs-target=".desc[data-id='{{ employee.id }}']" aria-expanded="false" aria-controls="collapseExample">
            {{ employee.name }}
        </span>
        <div class="e-actions col-2 d-flex align-items-center justify-content-center">
            <a href="{% url 'core:detail' id=employee.id%}"><i class="fa-solid fa-up-right-from-square" title="Przejdź do zadań pracownika"></i></a>
        </div>
        <div class="col-10 collapse fs-5 desc" data-id="{{ employee.id }}">
            {{ employee.description }}
        </div>
    </div>
    {% endfor %}
</main>
<div class="modal" tabindex="-1" id="e-add">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Dodaj pracownika</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" class="auth-form" enctype="multipart/form-data">
                <!-- TODO: Style form -->
                <div class="modal-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Zamknij</button>
                    <button type="submit" class="btn btn-primary">Dodaj</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock 'content' %}